# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
    #checkLatest: true
  displayName: 'Install Node.js'
  

- script: |
    npm i -g npminstall && npminstall
    npm run build
  displayName: 'npm install and build'
